
package interfaz;

import business.Person;
import java.io.File;
import java.text.SimpleDateFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.Period;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.SwingConstants;
import javax.swing.JComboBox;
import java.awt.Component;

import javax.imageio.IIOException;
import javax.swing.DefaultComboBoxModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.Color;
import java.awt.event.ItemListener;
import java.awt.event.ItemEvent;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class CreateJPanel extends javax.swing.JPanel {
	
String departamento;


    /**
     * Creates new form ControlJPanel
     */
	
	enum Departamento {
		MARKETING,TIC,ADMINISTRACIÓN
	}
    Person person;
    public CreateJPanel(Person person) {
        initComponents();
        this.person=person;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    
    
  
    private void initComponents() {

        crearPerfiljLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        picTextPath = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelLocalización = new javax.swing.JLabel();
        jLabelfnacimiento = new javax.swing.JLabel();
        jLabelTeléfono = new javax.swing.JLabel();
        jLabelDepartamento = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelnSeguridadSocial = new javax.swing.JLabel();
        jLabelCuentaBancaria = new javax.swing.JLabel();
        jLabelIncorporacion = new javax.swing.JLabel();
        nombreTextField = new javax.swing.JTextField();
        fechaIncorporacionTextField = new javax.swing.JTextField();
        LocalizaciónTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        seguridadSocialTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        bancoTextField = new javax.swing.JTextField();
        fechaNacimientoTextField = new javax.swing.JTextField();
		
        
		
        
		

        
        LocalizaciónTextField.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		Pattern pat = Pattern.compile("^[A-Za-zÑñÁáÉéÍíÓóÚúÜü ]{1,50}$");
				Matcher mat = pat.matcher(LocalizaciónTextField.getText());
				if (!mat.matches()) {
					LocalizaciónTextField.setText("Error");
					
        	}
        	}
        	
        	
        });
       
        nombreTextField.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		Pattern pat = Pattern.compile("^[A-Za-zÑñÁáÉéÍíÓóÚúÜü ]{1,50}$");
				Matcher mat = pat.matcher(nombreTextField.getText());
				if (!mat.matches()) {
					nombreTextField.setText("Error");
	
				}
        	}
        	
        	
        });
       
        phoneTextField.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		Pattern pat = Pattern.compile("^[67]\\d{8}$");
				Matcher mat = pat.matcher(phoneTextField.getText());
				if (!mat.matches()) {
					phoneTextField.setText("Error");
				
        	}
        		
        	}
        	
        });
        
        seguridadSocialTextField.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		Pattern pat = Pattern.compile("^\\d{10}$");
				Matcher mat = pat.matcher(seguridadSocialTextField.getText());
				if (!mat.matches()) {
					seguridadSocialTextField.setText("Error");
					
        	}
        	}
        	
        	
        	
        });
       
        emailTextField.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		Pattern pat = Pattern.compile("^\\w+@\\w+\\.[a-z]{2,3}$");
				Matcher mat = pat.matcher(emailTextField.getText());
				if (!mat.matches()) {
					emailTextField.setText("Error");
					
        	}
        	}
        	
        	
        });
      
        bancoTextField.addFocusListener(new FocusAdapter() {
        	@Override
        	public void focusLost(FocusEvent e) {
        		Pattern pat = Pattern.compile("^ES\\d{2}-\\d{4}-\\d{4}-\\d{2}-\\d{10}$");
				Matcher mat = pat.matcher(bancoTextField.getText());
				if (!mat.matches()) {
					bancoTextField.setText("Error");
					
        	}
        		
        	}
        	
        });
        
       
        JComboBox departamentocomboBox = new JComboBox();
        departamentocomboBox.addItemListener(new ItemListener() {
        	
        	public void itemStateChanged(ItemEvent e) {
        		int opcion;
        		
            	opcion = departamentocomboBox.getSelectedIndex();
        		switch(opcion) {
        		case 0:
        			departamento = "Marketing";
        			break;
        		case 1:
        			departamento = "TIC";
        			break;
        		case 2:
        			departamento = "Administración";
        		}
        	}
        });
        
        crearPerfiljLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        crearPerfiljLabel1.setText("Crear Perfil");

        jButton1.setText("Select Photo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        
        
        picTextPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                picTextPathActionPerformed(evt);
            }
        });
    
        	
        

        createBtn.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        createBtn.setText("Crear");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });

        jLabelNombre.setText("Nombre:");

        jLabelLocalización.setText("Localización:");

        jLabelfnacimiento.setText("Fecha nacimiento: ");

        jLabelTeléfono.setText("Teléfono:");

        jLabelDepartamento.setText("Departamento:");

        jLabelEmail.setText("Email: ");

        jLabelnSeguridadSocial.setText("Número Seguridad Social: ");

        jLabelCuentaBancaria.setText("Número Cuenta Bancaria:");

        jLabelIncorporacion.setText("Fecha incorporación:");

        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });
        
        
     
        departamentocomboBox.setModel(new DefaultComboBoxModel(new String[] {"Marketing", "TIC", "Administración"}));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(59)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabelnSeguridadSocial)
        						.addComponent(jLabelCuentaBancaria)
        						.addComponent(jLabelIncorporacion)
        						.addComponent(jLabelLocalización)
        						.addComponent(jLabelNombre)
        						.addComponent(jLabelDepartamento))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(fechaIncorporacionTextField, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        						.addComponent(nombreTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(LocalizaciónTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(fechaNacimientoTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(phoneTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(departamentocomboBox, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(emailTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(seguridadSocialTextField, Alignment.TRAILING, 244, 244, 244)
        						.addComponent(bancoTextField, Alignment.TRAILING, 244, 244, 244))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(picTextPath, GroupLayout.PREFERRED_SIZE, 149, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jButton1))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(59)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabelEmail, Alignment.LEADING)
        						.addComponent(jLabelTeléfono, Alignment.LEADING)
        						.addComponent(jLabelfnacimiento, Alignment.LEADING))
        					.addGap(541)))
        			.addGap(0))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(257)
        			.addComponent(crearPerfiljLabel1)
        			.addContainerGap(299, Short.MAX_VALUE))
        		.addGroup(layout.createSequentialGroup()
        			.addGap(272)
        			.addComponent(createBtn)
        			.addContainerGap(341, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(47)
        			.addComponent(crearPerfiljLabel1)
        			.addGap(18)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(jLabelNombre)
        					.addGap(18)
        					.addComponent(jLabelLocalización))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(nombreTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(picTextPath, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jButton1))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(LocalizaciónTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabelfnacimiento)
        				.addComponent(fechaNacimientoTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jLabelTeléfono)
        				.addComponent(phoneTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGap(4)
        					.addComponent(departamentocomboBox, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        				.addGroup(layout.createSequentialGroup()
        					.addGap(11)
        					.addComponent(jLabelDepartamento)
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addComponent(jLabelEmail)))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabelnSeguridadSocial)
        						.addComponent(seguridadSocialTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jLabelCuentaBancaria))
        				.addComponent(bancoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelIncorporacion)
        				.addComponent(fechaIncorporacionTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addGap(31)
        			.addComponent(createBtn)
        			.addContainerGap(22, Short.MAX_VALUE))
        );
        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {nombreTextField, departamentocomboBox, LocalizaciónTextField, fechaNacimientoTextField, phoneTextField, seguridadSocialTextField, emailTextField, bancoTextField, fechaIncorporacionTextField});
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f= chooser.getSelectedFile();
        String fileName= f.getAbsolutePath();
        picTextPath.setText(fileName);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void picTextPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_picTextPathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_picTextPathActionPerformed

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
    	
    try {	
    	String fechaNacimiento = fechaNacimientoTextField.getText();
		SimpleDateFormat formatoNacimiento = new SimpleDateFormat("dd/MM/yyyy");
		
		String fechaIncorporacion = fechaIncorporacionTextField.getText();
		SimpleDateFormat formatoIncorporacion = new SimpleDateFormat("dd/MM/yyyy");
		
		if (fechaNacimiento.equals("")) {
			

		} else {
			LocalDate comprobarFechaNacimiento = LocalDate.parse(fechaNacimiento,
					DateTimeFormatter.ofPattern("dd/MM/yyyy"));
			
			LocalDate comprobarFechaIncorporacion = LocalDate.parse(fechaIncorporacion,DateTimeFormatter.ofPattern("dd/MM/yyyy"));
			
			Period edad = Period.between(comprobarFechaNacimiento, comprobarFechaIncorporacion);
			int años = edad.getYears();
			if (edad.getYears() < 18) {
				JOptionPane.showMessageDialog(null, "El empleado es menor de edad");
			
		}else if (picTextPath.getText().isEmpty() || nombreTextField.getText().isEmpty()
						|| fechaNacimientoTextField.getText().isEmpty() || bancoTextField.getText().isEmpty()
						|| emailTextField.getText().isEmpty() || seguridadSocialTextField.getText().isEmpty()
						|| phoneTextField.getText().isEmpty() || departamento.isEmpty()
						|| LocalizaciónTextField.getText().isEmpty()
						|| fechaIncorporacionTextField.getText().isEmpty()) {
					JOptionPane.showMessageDialog(null, "Debe completar todos los campos");
					
			} else if (nombreTextField.getText().equals("Error") || picTextPath.getText().equals("Error") 
					|| fechaNacimientoTextField.getText().equals("Error") || bancoTextField.getText().equals("Error")
					|| emailTextField.getText().equals("Error") || seguridadSocialTextField.getText().equals("Error")
					|| phoneTextField.getText().equals("Error") ||  LocalizaciónTextField.getText().equals("Error")
					|| fechaIncorporacionTextField.getText().equals("Error")) {
				JOptionPane.showMessageDialog(null, "Los datos son erróneos");
			}
		
		else {
				
				 person.setImageTxt(picTextPath.getText());
	    	  	  person.setName(nombreTextField.getText());
	    	      person.setFechaNacimiento(fechaNacimientoTextField.getText());
	    	      person.setBankAccNum(bancoTextField.getText());
	    	      person.setEmail(emailTextField.getText());
	    	      person.setSsn(seguridadSocialTextField.getText());
	    	      person.setPhone(phoneTextField.getText());
	    	      person.setGeographic_data(LocalizaciónTextField.getText());
	    	      person.setFechaIncorporacion(fechaIncorporacionTextField.getText());
	    	      person.setDepartamento(departamento);
	    	      
	    	     person.setCódigo(person.contador++);
	    	      JOptionPane.showMessageDialog(null, "Perfil creado correctamente !!!");

			}
		}
		 
    }catch(DateTimeParseException error ) {
    	JOptionPane.showMessageDialog(null, "Fechas mal introducidas");
    }catch(NullPointerException error2) {
    	JOptionPane.showMessageDialog(null, "Departamento está vacío");
    }
   
        
    }//GEN-LAST:event_createBtnActionPerformed

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bancoTextField;
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField fechaNacimientoTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField LocalizaciónTextField;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel crearPerfiljLabel1;
    private javax.swing.JLabel jLabelIncorporacion;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelLocalización;
    private javax.swing.JLabel jLabelfnacimiento;
    private javax.swing.JLabel jLabelTeléfono;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JComboBox DepartamentocomboBox;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelnSeguridadSocial;
    private javax.swing.JLabel jLabelCuentaBancaria;
    private javax.swing.JTextField fechaIncorporacionTextField;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField picTextPath;
    private javax.swing.JTextField seguridadSocialTextField;
}