
package interfaz;

import business.Person;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.JComboBox;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import java.awt.Component;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

public class DisplayJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJPanel
     */
    //Person person;
    public DisplayJPanel(Person person) {
        initComponents();
       // this.person=person;
        displayPerson(person);
    }
    
    public void displayPerson(Person person){
        
        nombreTextField.setText(person.getName());
        emailTextField.setText(person.getEmail());
        seguridadSocialTextField.setText(person.getSsn());
        NacimientoTextField.setText(person.getFechaNacimiento());
        LocalizacionTextField.setText(person.getGeographic_data());
        bancoTextField.setText(person.getBankAccNum());
        IncorporacionTextField.setText(person.getFechaIncorporacion());
        phoneTextField.setText(person.getPhone());
        textFieldCodigoEmpleado.setText(String.valueOf(person.getCódigo()));
        textFieldDepartamento.setText(person.getDepartamento());
       
        
        String imageTxt= person.getImagetxt();
       // imagePatTxt.setText(imageTxt);
        
        try {
            BufferedImage img = ImageIO.read(new File(imageTxt));

            imageLabel.setBounds(100, 100, 280, 250);

            Image dimg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(),
                    Image.SCALE_SMOOTH);
            ImageIcon icon = new ImageIcon(dimg);

            imageLabel.setIcon(icon);
        } catch (IOException e) {
            e.printStackTrace();
        }
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imageLabel = new javax.swing.JLabel();
        NacimientoTextField = new javax.swing.JTextField();
        nombrejLabel = new javax.swing.JLabel();
        LocalizaciónjLabel = new javax.swing.JLabel();
        jLabelfnacimiento = new javax.swing.JLabel();
        jLabelTeléfono = new javax.swing.JLabel();
        jLabelDepartamento = new javax.swing.JLabel();
        jLabelemail = new javax.swing.JLabel();
        jLabelnSeguridadSocial = new javax.swing.JLabel();
        jLabelbanco = new javax.swing.JLabel();
        jLabelIncorporacion = new javax.swing.JLabel();
        IncorporacionTextField = new javax.swing.JTextField();
        bancoTextField = new javax.swing.JTextField();
        seguridadSocialTextField = new javax.swing.JTextField();
        emailTextField = new javax.swing.JTextField();
        phoneTextField = new javax.swing.JTextField();
        LocalizacionTextField = new javax.swing.JTextField();
        nombreTextField = new javax.swing.JTextField();
        nombreTextField.setEditable(false);
        mostrarPerfiljLabel1 = new javax.swing.JLabel();
        
        imageLabel.setBackground(new java.awt.Color(102, 102, 102));
        imageLabel.setOpaque(true);

        NacimientoTextField.setEditable(false);

        nombrejLabel.setText("Nombre:");

        LocalizaciónjLabel.setText("Localizacion");

        jLabelfnacimiento.setText("Fecha nacimiento");

        jLabelTeléfono.setText("Teléfono:");

        jLabelDepartamento.setText("Departamento:");

        jLabelemail.setText("Email: ");

        jLabelnSeguridadSocial.setText("Número Seguridad Social: ");

        jLabelbanco.setText("Número Cuenta Bancaria: ");

        jLabelIncorporacion.setText("Fecha Incorporación ");

        IncorporacionTextField.setEditable(false);

        bancoTextField.setEditable(false);

        seguridadSocialTextField.setEditable(false);

        emailTextField.setEditable(false);
        emailTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTextFieldActionPerformed(evt);
            }
        });

        phoneTextField.setEditable(false);

        LocalizacionTextField.setEditable(false);

        mostrarPerfiljLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        mostrarPerfiljLabel1.setText("Mostrar Perfil");
        
        textFieldCodigoEmpleado = new JTextField();
        textFieldCodigoEmpleado.setText((String) null);
        textFieldCodigoEmpleado.setEditable(false);
        
        JLabel lblCdigoEmpleado = new JLabel();
        lblCdigoEmpleado.setText("Código Empleado:");
        
        textFieldDepartamento = new JTextField();
        textFieldDepartamento.setText((String) null);
        textFieldDepartamento.setEditable(false);
        
       

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.CENTER)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(64)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabelnSeguridadSocial)
        						.addComponent(jLabelbanco)
        						.addComponent(jLabelIncorporacion)
        						.addComponent(lblCdigoEmpleado, GroupLayout.PREFERRED_SIZE, 147, GroupLayout.PREFERRED_SIZE)
        						.addComponent(LocalizaciónjLabel)
        						.addComponent(nombrejLabel)
        						.addComponent(jLabelDepartamento))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(nombreTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(LocalizacionTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(NacimientoTextField, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        						.addComponent(phoneTextField, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        						.addComponent(textFieldDepartamento, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(emailTextField, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
        						.addComponent(seguridadSocialTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(bancoTextField, Alignment.TRAILING, 244, 244, 244)
        						.addComponent(IncorporacionTextField, Alignment.TRAILING, 244, 244, 244)
        						.addComponent(textFieldCodigoEmpleado, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 244, GroupLayout.PREFERRED_SIZE)
        						.addComponent(mostrarPerfiljLabel1, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, 212, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addComponent(jLabelemail, Alignment.LEADING)
        						.addComponent(jLabelTeléfono, Alignment.LEADING)
        						.addComponent(jLabelfnacimiento, Alignment.LEADING))
        					.addGap(0, 319, Short.MAX_VALUE)))
        			.addGap(15)
        			.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 269, GroupLayout.PREFERRED_SIZE)
        			.addGap(25))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(88)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(imageLabel, GroupLayout.PREFERRED_SIZE, 238, GroupLayout.PREFERRED_SIZE)
        				.addGroup(layout.createSequentialGroup()
        					.addComponent(mostrarPerfiljLabel1)
        					.addGap(18)
        					.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(nombrejLabel)
        							.addGap(18)
        							.addComponent(LocalizaciónjLabel))
        						.addGroup(layout.createSequentialGroup()
        							.addComponent(nombreTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        							.addPreferredGap(ComponentPlacement.RELATED)
        							.addComponent(LocalizacionTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabelfnacimiento)
        						.addComponent(NacimientoTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jLabelTeléfono)
        						.addComponent(phoneTextField, Alignment.TRAILING, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addGap(11)
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabelDepartamento)
        						.addComponent(textFieldDepartamento, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.RELATED)
        					.addGroup(layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(emailTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        						.addComponent(jLabelemail))))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.TRAILING)
        				.addGroup(layout.createSequentialGroup()
        					.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        						.addComponent(jLabelnSeguridadSocial)
        						.addComponent(seguridadSocialTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jLabelbanco))
        				.addComponent(bancoTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jLabelIncorporacion)
        				.addComponent(IncorporacionTextField, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE))
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(textFieldCodigoEmpleado, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
        				.addComponent(lblCdigoEmpleado))
        			.addContainerGap(111, Short.MAX_VALUE))
        );
        layout.linkSize(SwingConstants.HORIZONTAL, new Component[] {NacimientoTextField, IncorporacionTextField, bancoTextField, seguridadSocialTextField, emailTextField, phoneTextField, LocalizacionTextField, nombreTextField, textFieldCodigoEmpleado, textFieldDepartamento});
        this.setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents

    private void emailTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bancoTextField;
    private javax.swing.JTextField NacimientoTextField;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JTextField LocalizacionTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel mostrarPerfiljLabel1;
    private javax.swing.JLabel jLabelIncorporacion;
    private javax.swing.JLabel nombrejLabel;
    private javax.swing.JLabel LocalizaciónjLabel;
    private javax.swing.JLabel jLabelfnacimiento;
    private javax.swing.JLabel jLabelTeléfono;
    private javax.swing.JLabel jLabelDepartamento;
    private javax.swing.JLabel jLabelemail;
    private javax.swing.JLabel jLabelnSeguridadSocial;
    private javax.swing.JLabel jLabelbanco;
    private javax.swing.JTextField IncorporacionTextField;
    private javax.swing.JTextField nombreTextField;
    private javax.swing.JTextField phoneTextField;
    private javax.swing.JTextField seguridadSocialTextField;
    private JTextField textFieldCodigoEmpleado;
    private JTextField textFieldDepartamento;
}