/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import business.Person;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.Font;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Scanner;
import java.awt.event.ActionEvent;
import javax.swing.SwingConstants;
import java.awt.Component;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author ankit
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    Person person;
    public MainJFrame() {
        initComponents();
        person= new Person();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        controlJPanel = new javax.swing.JPanel();
        createPerson = new javax.swing.JButton();
        viewPerson = new javax.swing.JButton();
        displayJPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createPerson.setText("Crear Perfil");
        createPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPersonActionPerformed(evt);
            }
        });

        viewPerson.setText("Mostrar Perfil");
        viewPerson.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewPersonActionPerformed(evt);
            }
        });
        
        btnCargarPerfil = new JButton();
        btnCargarPerfil.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		
				FileReader lectura;
				try {
					lectura = new FileReader("login.txt");
					BufferedReader br = new BufferedReader(lectura);
					Scanner s = new Scanner(br);
					
				while() {
						person.setName(s.next());
						person.setGeographic_data(s.next());
			
    	        		person.setFechaNacimiento(s.next());
    	        		person.setPhone(s.next());
    	        		person.setDepartamento(s.next());
    	        		
    	        		person.setEmail(s.next());
    	        		person.setSsn(s.next());
    	        		person.setFechaIncorporacion(s.next());
    	        		person.setBankAccNum(s.next());
    	        		person.setCódigo(s.nextInt());
    	        		 person.setImageTxt(s.next());
						
					br.close();
				}
				} catch (IOException error) {

					
				}
        	}
        });
        btnCargarPerfil.setText("Cargar Perfil");
        
        JButton btnGuardar = new JButton("Guardar Perfil");
        btnGuardar.addActionListener(new ActionListener() {
        	
        	public void actionPerformed(ActionEvent arg0) {
        		
        		try{
        			if(person.getName().isEmpty() || person.getGeographic_data().isEmpty() || person.getFechaIncorporacion().isEmpty() ||
        		
        				person.getBankAccNum().isEmpty() || person.getDepartamento().isEmpty() || person.getEmail().isEmpty() ||
        				person.getFechaNacimiento().isEmpty() || person.getPhone().isEmpty() || person.getImagetxt().isEmpty() || person.getSsn().isEmpty()) {
        				
        			}else {
        	        		
        	        		FileWriter escribir;

        	        		try {
        	        			escribir = new FileWriter("login.txt");
        	        			BufferedWriter bw = new BufferedWriter(escribir);
        	        			PrintWriter pw = new PrintWriter(bw);

        	        			pw.println(person.getName() + "\n"  + person.getGeographic_data() + "\n"  + 
        	        			person.getFechaNacimiento()	+"\n " + person.getPhone() + "\n" + person.getDepartamento() + "\n" +
        	        			person.getEmail() + "\n" + person.getSsn() + "\n" +
        	        			person.getFechaIncorporacion() + "\n"  + person.getBankAccNum()+ "\n" +
        	        			 person.getCódigo() + "\n" + person.getImagetxt()); // Para imprimir en el fichero
        	        			pw.close();
        	        			JOptionPane.showMessageDialog(null, "Perfil guardado correctamente");
        	        		} catch (IOException error) {
        	        			
        	        		}
        	
        		}
        			
        		}catch(NullPointerException error) {
        		
        			JOptionPane.showMessageDialog(null, "No hay ningún perfil creado");
        		}
        	}
        });
        

        javax.swing.GroupLayout controlJPanelLayout = new javax.swing.GroupLayout(controlJPanel);
        controlJPanelLayout.setHorizontalGroup(
        	controlJPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(controlJPanelLayout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(controlJPanelLayout.createParallelGroup(Alignment.LEADING)
        				.addComponent(btnGuardar, GroupLayout.PREFERRED_SIZE, 133, GroupLayout.PREFERRED_SIZE)
        				.addComponent(createPerson)
        				.addComponent(viewPerson)
        				.addComponent(btnCargarPerfil, GroupLayout.PREFERRED_SIZE, 97, GroupLayout.PREFERRED_SIZE))
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        controlJPanelLayout.setVerticalGroup(
        	controlJPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(controlJPanelLayout.createSequentialGroup()
        			.addGap(94)
        			.addComponent(createPerson)
        			.addGap(63)
        			.addComponent(viewPerson)
        			.addGap(70)
        			.addComponent(btnCargarPerfil)
        			.addGap(50)
        			.addComponent(btnGuardar)
        			.addContainerGap(93, Short.MAX_VALUE))
        );
        controlJPanelLayout.linkSize(SwingConstants.HORIZONTAL, new Component[] {createPerson, viewPerson, btnCargarPerfil, btnGuardar});
        controlJPanel.setLayout(controlJPanelLayout);

        jSplitPane1.setLeftComponent(controlJPanel);
        
        lblError = new JLabel("");
        lblError.setFont(new Font("Dialog", Font.BOLD, 20));
        
        JLabel lblErrorcargarPerfil = new JLabel("");
        lblErrorcargarPerfil.setFont(new Font("Dialog", Font.BOLD, 20));

        javax.swing.GroupLayout displayJPanelLayout = new javax.swing.GroupLayout(displayJPanel);
        displayJPanelLayout.setHorizontalGroup(
        	displayJPanelLayout.createParallelGroup(Alignment.LEADING)
        		.addGroup(displayJPanelLayout.createSequentialGroup()
        			.addGap(56)
        			.addComponent(lblError, GroupLayout.PREFERRED_SIZE, 279, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(lblErrorcargarPerfil, GroupLayout.PREFERRED_SIZE, 486, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(389, Short.MAX_VALUE))
        );
        displayJPanelLayout.setVerticalGroup(
        	displayJPanelLayout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(displayJPanelLayout.createSequentialGroup()
        			.addContainerGap(172, Short.MAX_VALUE)
        			.addComponent(lblErrorcargarPerfil, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE)
        			.addGap(162))
        		.addGroup(Alignment.LEADING, displayJPanelLayout.createSequentialGroup()
        			.addGap(219)
        			.addComponent(lblError)
        			.addContainerGap(251, Short.MAX_VALUE))
        );
        displayJPanel.setLayout(displayJPanelLayout);

        jSplitPane1.setRightComponent(displayJPanel);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPersonActionPerformed
        // TODO add your handling code here:
    	
    	
        CreateJPanel createJPanel= new CreateJPanel(person);
        jSplitPane1.setRightComponent(createJPanel);
        
        
    }//GEN-LAST:event_createPersonActionPerformed

    private void btnCargarPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonActionPerformed
        // TODO add your handling code here:
    	
    	try{
    		DisplayJPanel viewJPanel= new DisplayJPanel(person);
    		  jSplitPane1.setRightComponent(viewJPanel);
    	}catch(NullPointerException error2) {
    		lblErrorcargarPerfil.setText("Error no hay ningún perfil guardado");
    		
    	}
      
        
        
    }//GEN-LAST:event_viewPersonActionPerformed
    
    private void viewPersonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewPersonActionPerformed
        // TODO add your handling code here:
    try {
        DisplayJPanel viewJPanel= new DisplayJPanel(person);
        jSplitPane1.setRightComponent(viewJPanel);
    }catch(NullPointerException error1) {
    	lblError.setText("Error perfil no creado");
    	
    }
        
        
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel controlJPanel;
    private javax.swing.JButton createPerson;
    private javax.swing.JPanel displayJPanel;
    private javax.swing.JSplitPane jSplitPane1;
    private JLabel lblError;
    private JButton btnCargarPerfil;
    private JButton viewPerson;
    private JLabel lblErrorcargarPerfil;
}